### ISSUE TITLE
环境依赖问题：DLL load failed while importing flash_attn_2_cuda

### ISSUE THREAD

**Issue by junglehu** [chaojie/ComfyUI-DragNUWA#12]
如题，其他环境都安装上了，flash_attn组件也尝试重新安装，但是这个flash_attn是没解决。

> Logs
Traceback (most recent call last):
  File "E:\AIGC\ComfyUI_windows\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 12, in <module>
    from .DragNUWA_net import Net, args
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\DragNUWA_net.py", line 5, in <module>
    from .dragnuwa.svd.modules.diffusionmodules.video_model_flow import VideoUNet_flow, VideoResBlock_Embed
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\encoders\modules.py", line 6, in <module>
    import kornia
  File "E:\Python\Python310\lib\site-packages\kornia\__init__.py", line 8, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\__init__.py", line 2, in <module>
    from kornia.augmentation import auto, container
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\auto\__init__.py", line 1, in <module>
    from .autoaugment import AutoAugment
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\auto\autoaugment\__init__.py", line 1, in <module>
    from .autoaugment import AutoAugment
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\auto\autoaugment\autoaugment.py", line 5, in <module>
    from kornia.augmentation.auto.base import SUBPLOLICY_CONFIG, PolicyAugmentBase
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\auto\base.py", line 5, in <module>
    from kornia.augmentation.auto.operations.base import OperationBase
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\auto\operations\__init__.py", line 3, in <module>
    from .policy import PolicySequential
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\auto\operations\policy.py", line 7, in <module>
    from kornia.augmentation.container.base import ImageSequentialBase, TransformMatrixMinIn
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\container\__init__.py", line 1, in <module>
    from kornia.augmentation.container.augment import AugmentationSequential
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\container\augment.py", line 4, in <module>
    from kornia.augmentation._2d.base import RigidAffineAugmentationBase2D
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\_2d\__init__.py", line 2, in <module>
    from kornia.augmentation._2d.intensity import *
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\_2d\intensity\__init__.py", line 21, in <module>
    from kornia.augmentation._2d.intensity.plasma import RandomPlasmaBrightness, RandomPlasmaContrast, RandomPlasmaShadow
  File "E:\Python\Python310\lib\site-packages\kornia\augmentation\_2d\intensity\plasma.py", line 5, in <module>
    from kornia.contrib import diamond_square
  File "E:\Python\Python310\lib\site-packages\kornia\contrib\__init__.py", line 15, in <module>
    from .image_stitching import ImageStitcher
  File "E:\Python\Python310\lib\site-packages\kornia\contrib\image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "E:\Python\Python310\lib\site-packages\kornia\feature\__init__.py", line 6, in <module>
    from .integrated import (
  File "E:\Python\Python310\lib\site-packages\kornia\feature\integrated.py", line 16, in <module>
    from .lightglue import LightGlue
  File "E:\Python\Python310\lib\site-packages\kornia\feature\lightglue.py", line 16, in <module>
    from flash_attn.modules.mha import FlashCrossAttention
  File "E:\Python\Python310\lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "E:\Python\Python310\lib\site-packages\flash_attn\flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: 找不到指定的模块。

Cannot import E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA module for custom nodes: DLL load failed while importing flash_attn_2_cuda: 找不到指定的模块。

**Comment by Suiji12** [comment]
请问解决了吗？
