### ISSUE TITLE
AssertionError when running optical flow workflow

### ISSUE THREAD

**Issue by whmc76** [chaojie/ComfyUI-DragNUWA#22]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 498, in run_inference
    return model.run_brush(image_pil, motion_brush, inference_batch_size, motion_bucket_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 380, in run_brush
    outputs = self.forward_sample(
              ^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 175, in forward_sample
    samples_z = self.drag_nuwa_net.sampler(denoiser, randn, cond=c, uc=uc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\sampling.py", line 120, in __call__
    x = self.sampler_step(
        ^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\sampling.py", line 99, in sampler_step
    denoised = self.denoise(x, denoiser, sigma_hat, cond, uc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\sampling.py", line 55, in denoise
    denoised = denoiser(*self.guider.prepare_inputs(x, sigma, cond, uc))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 173, in denoiser
    return self.drag_nuwa_net.denoiser(self.drag_nuwa_net.model, input, sigma, c, **additional_model_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\denoiser.py", line 37, in forward
    network(input * c_in, c_noise, cond, **additional_model_inputs) * c_out
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\wrappers.py", line 28, in forward
    return self.diffusion_model(
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\video_model_flow.py", line 1270, in forward
    assert y.shape[0] == x.shape[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
![image](https://github.com/chaojie/ComfyUI-DragNUWA/assets/129386342/8c268e3b-d35f-444b-915f-61bafb746ae7)

**Comment by quanhaol** [comment]
I found that if you set model_length to 14, this will be solved.
