### ISSUE TITLE
Error running DragRun node

### ISSUE THREAD

**Issue by Niutonian** [chaojie/ComfyUI-DragNUWA#3]
I downloaded the model and placed it in the right location, but I still get this error:

'''' 0%|                                                                                            | 0/1 [00:00<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 251, in run_inference
    return model.run(image_pil, tracking_points, inference_batch_size, motion_bucket_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 185, in run
    outputs = self.forward_sample(
              ^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 108, in forward_sample
    c, uc = self.drag_nuwa_net.conditioner.get_unconditional_conditioning(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\encoders\modules.py", line 180, in get_unconditional_conditioning
    c = self(batch_c, force_cond_zero_embeddings)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\encoders\modules.py", line 133, in forward
    emb_out = embedder(batch[embedder.input_key])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\encoders\modules.py", line 1013, in forward
    out = self.encoder.encode(vid[n * n_samples : (n + 1) * n_samples])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\models\autoencoder.py", line 472, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\model.py", line 594, in forward
    h = self.mid.attn_1(h)
        ^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\model.py", line 263, in forward
    h_ = self.attention(h_)
         ^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\diffusionmodules\model.py", line 249, in attention
    out = xformers.ops.memory_efficient_attention(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\__init__.py", line 337, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\dispatch.py", line 120, in _dispatch_fw
    return _run_priority_list(
           ^^^^^^^^^^^^^^^^^^^
  File "E:\COMFYUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\dispatch.py", line 63, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2880, 1, 512) (torch.float32)
     key         : shape=(1, 2880, 1, 512) (torch.float32)
     value       : shape=(1, 2880, 1, 512) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 128
    xFormers wasn't build with CUDA support
    attn_bias type is <class 'NoneType'>
    operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 256
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 128
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 512

Prompt execu'''

**Comment by guahunyo** [comment]
+1

**Comment by guahunyo** [comment]
作者好像一直在开发新的 老问题都不怎么修

**Comment by Positliver** [comment]
这个报错原因是xformers版本和cuda版本不匹配
解决方法：
#查看xformers信息
python -m xformers.info
# cuda 11.8 version
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu118
# cuda 12.1 version
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121
------------
https://github.com/facebookresearch/xformers#installing-xformers

**Comment by CoUIfy** [comment]
Translation?
