### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by junglehu** [chaojie/ComfyUI-DragNUWA#4]
出现下面的错误代码，看起来是需要调用 CLIP-ViT-H-14-laion2B-s32B-b79K 这个 clip_vision的模型，但是这个我已经下载到本地了，是否可以存放在本地进行调用？

(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))"), '(Request ID: 97b952e0-3003-4d7c-8f5f-47417dd5fe9f)')

Traceback (most recent call last):
  File "E:\AIGC\ComfyUI_windows\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AIGC\ComfyUI_windows\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AIGC\ComfyUI_windows\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 223, in load_dragnuwa
    DragNUWA_net = Drag("cuda:0", ckpt_path, f'{comfy_path}/custom_nodes/ComfyUI-DragNUWA/DragNUWA_net.py', height, width, model_length)
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\nodes.py", line 74, in __init__
    drag_nuwa_net = Net(args)
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\DragNUWA_net.py", line 250, in __init__
    self.conditioner = GeneralConditioner(args.conditioner_emb_models)
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\encoders\modules.py", line 79, in __init__
    embedder = instantiate_from_config(embconfig)
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\encoders\modules.py", line 1040, in __init__
    self.open_clip = instantiate_from_config(open_clip_embedding_config)
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\AIGC\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-DragNUWA\dragnuwa\svd\modules\encoders\modules.py", line 592, in __init__
    model, _, _ = open_clip.create_model_and_transforms(
  File "E:\Python\Python310\lib\site-packages\open_clip\factory.py", line 382, in create_model_and_transforms
    model = create_model(
  File "E:\Python\Python310\lib\site-packages\open_clip\factory.py", line 281, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "E:\Python\Python310\lib\site-packages\open_clip\pretrained.py", line 552, in download_pretrained
    target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
  File "E:\Python\Python310\lib\site-packages\open_clip\pretrained.py", line 522, in download_pretrained_from_hf
    cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
  File "E:\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "E:\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
    r = _request_wrapper(
  File "E:\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "E:\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "E:\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Python\Python310\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "E:\Python\Python310\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))"), '(Request ID: 3d361a64-b48c-4a8e-b386-030ce40d5506)')a

**Comment by junglehu** [comment]
I have already resolved this issue. I used a mirror site and executed the following commands in the command line:

**Comment by junglehu** [comment]
I have already resolved this issue. I used a mirror site and executed the following commands in the command line:
pip install -U huggingface_hub
set HF_ENDPOINT= mirror websit
