### ISSUE TITLE
Followed all the steps and installed all the processes, but still reported this error

### ISSUE THREAD

**Issue by jinljin** [chaojie/ComfyUI-DragNUWA#8]
Traceback (most recent call last):
  File "/data03/lxl_workspace/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data03/lxl_workspace/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data03/lxl_workspace/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/nodes.py", line 223, in load_dragnuwa
    DragNUWA_net = Drag("cuda:0", ckpt_path, f'{comfy_path}/custom_nodes/ComfyUI-DragNUWA/DragNUWA_net.py', height, width, model_length)
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/nodes.py", line 74, in __init__
    drag_nuwa_net = Net(args)
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/DragNUWA_net.py", line 250, in __init__
    self.conditioner = GeneralConditioner(args.conditioner_emb_models)
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/dragnuwa/svd/modules/encoders/modules.py", line 79, in __init__
    embedder = instantiate_from_config(embconfig)
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/dragnuwa/svd/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/dragnuwa/svd/modules/encoders/modules.py", line 1040, in __init__
    self.open_clip = instantiate_from_config(open_clip_embedding_config)
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/dragnuwa/svd/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/data03/lxl_workspace/ComfyUI/custom_nodes/ComfyUI-DragNUWA/dragnuwa/svd/modules/encoders/modules.py", line 592, in __init__
    model, _, _ = open_clip.create_model_and_transforms(
  File "/data03/lxl_workspace/miniconda3/envs/comfy-new/lib/python3.10/site-packages/open_clip/factory.py", line 382, in create_model_and_transforms
    model = create_model(
  File "/data03/lxl_workspace/miniconda3/envs/comfy-new/lib/python3.10/site-packages/open_clip/factory.py", line 281, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "/data03/lxl_workspace/miniconda3/envs/comfy-new/lib/python3.10/site-packages/open_clip/pretrained.py", line 552, in download_pretrained
    target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
  File "/data03/lxl_workspace/miniconda3/envs/comfy-new/lib/python3.10/site-packages/open_clip/pretrained.py", line 522, in download_pretrained_from_hf
    cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
  File "/data03/lxl_workspace/miniconda3/envs/comfy-new/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/data03/lxl_workspace/miniconda3/envs/comfy-new/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by chaojie** [comment]
https://hf-mirror.com/
